#!/bin/bash

name=$(date '+%Y-%m-%d__%H:%M:%S.png')
scrot -s -q 100 $name

if [[ -f "$name" ]]; then
    if [[ ! -d "~/screenshots" ]]; then
        mkdir -p ~/screenshots
    fi
    mv $name ~/screenshots
fi

